[package]
name = "secure_sum"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", default-features = false }
thiserror = { version = "2.0", default-features = false }

[dev-dependencies]
tempfile = { version = "3.14", default-features = false }
