hasRecentCommits = 1 # We care about this probe
fuzzed = 0.4 # Good practice, but not as important for us as other criteria.
archived = -1 # Using archived repos is deprecated, so this probe gets a negative value
hasOSVVulnerabilities = -2 # Very important *not* to have this
hasPermissiveLicense = 0 # A value of zero is treated as if the field is not present, the probe is not run
