name: PR Checks

on: [pull_request]

jobs:
    check_licenses:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: EmbarkStudios/cargo-deny-action@v2

    rust-tests:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2
            - uses: clechasseur/rs-cargo@v1
              with:
                  command: test

    clippy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: clechasseur/rs-cargo@v1
              with:
                  command: clippy

    system-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: clechasseur/rs-cargo@v1
              with:
                  command: build
                  args: --release
            - run: |
                chmod +x ./system_tests/test.sh
                ./system_tests/test.sh
